### ISSUE TITLE
Ions Feature

### ISSUE THREAD

**Issue by vfonsecapv** [scalamolecule/molecule-old#23]
What do you guys think about having something like Ion or even run Molecule inside Datomic Ion?

**Comment by marcgrue** [comment]
Since Datomic hasn't released a Java API for their Cloud model (as opposed to the On-Prem model), Molecule hasn't been adapted to the Cloud model which is the only model that can run in Ions. Furthermore I think it's a Clojure-only environment. So the odds a  low that Molecule could be used in this environment. I'm not sure either what the benefits would be for a Scala application. Maybe you have some thoughts on this?

For advanced On-Prem deployment in the Cloud I found this video very interesting:
https://www.youtube.com/watch?v=vFX6T5oQC7Y
